language: php
php:
  - '7.0'
  - '7.3'
env:
  - MYSQL_HOST=159.89.232.129
  - MYSQL_DB=community_voices
  - MYSQL_USER=public_cv
  - MYSQL_PASS=1234
  - SERVER=TRAVIS_CI
before_script:
  - composer update
  - composer install
script:
  - php tests/bootstrap.php
notifications:
  email: false
  webhooks:
    urls:
      - http://environmentaldashboard.org/travis-ci/notifications?repo=community-voices
    on_success: always # default: always
    on_failure: never # default: always
    on_cancel: never # default: always
    on_error: never # default: always
  slack:
    rooms:
      - envdash:2Ml8eUe6ZTTOGDCcIHtjDaRb#devops
    on_success: change # default: always
    on_failure: always # default: always
