language: php
php:
  - '7.0'
  - '7.3'
env:
  - MYSQL_HOST=localhost
  - MYSQL_DB=community_voices
  - MYSQL_USER=root
  - MYSQL_PASS=pass
  - SERVER=TRAVIS_CI
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('pass') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -ppass
  - sudo service mysql restart
before_script:
  - mysql -u root -ppass -e 'CREATE DATABASE community_voices;'
  - mysql -u root -ppass community_voices < migrate/schema.sql
  - mysql -u root -ppass community_voices < migrate/defaults.sql
  - composer update
  - composer install
script:
  - php tests/bootstrap.php
notifications:
  email: false
  webhooks:
    urls:
      - http://environmentaldashboard.org/travis-ci/notifications?repo=community-voices
    on_success: always # default: always
    on_failure: never # default: always
    on_cancel: never # default: always
    on_error: never # default: always
  slack:
    rooms:
      - envdash:2Ml8eUe6ZTTOGDCcIHtjDaRb#devops
    on_success: change # default: always
    on_failure: always # default: always
